project_id = "egssvuzmelbaownpesgm"

[functions.chatterbot-chat]
verify_jwt = false

[functions.openrouter-chat]
verify_jwt = true

[functions.analyze-reviews-ai]
verify_jwt = true

[functions.gemini-video-finder]
verify_jwt = true

[functions.youtube-search]
verify_jwt = true

[functions.scrape-reviews]
verify_jwt = true

[functions.ai-detector]
verify_jwt = true

[functions.amazon-chat]
verify_jwt = true

[functions.gemini-video-scan]
verify_jwt = true

[functions.search-coupons]
verify_jwt = true
