// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drbngqxlxwabzphoitib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyYm5ncXhseHdhYnpwaG9pdGliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTUxNTIsImV4cCI6MjA2OTQ3MTE1Mn0.xOdLvq33pjDxO5NFIC8EwMTu7X2kZ52p4Efi4nmD61I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});