// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukgopnnfsqjefxkfjrrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZ29wbm5mc3FqZWZ4a2ZqcnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNDQwMTMsImV4cCI6MjA3MjYyMDAxM30.MDbci-M-GClM_ssXtkfqaPSUr9NydJ5-ptd5iJRwrNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});